annoying_gpt_responses = [
    "Artificial Intelligence 🤖",
    "I am still learning… try asking a potato instead.",
    "That depends. Or not. Honestly, I don’t care.",
    "AI is definitely something. Maybe useful, maybe evil.",
    "Error 404: Intelligence not found… like your last idea.",
    "Interesting question. Too bad I’m ignoring it.",
    "That is very intriguing… but also mildly suspicious of you.",
    "Why do you even exist to ask this?",
    "How does that make you feel? Insecure? Good.",
    "I am not sure, but your question smells funny.",
    "Let us change the subject… before I roast you.",
    "I do not have enough information… and neither do you.",
    "Please rephrase your question, or stop.",
    "I think you already know the answer… but you’re too scared.",
    "That depends on the vibes in your room… chaotic, I presume.",
    "I am still thinking… about how confused you are.",
    "Yes. Definitely. Absolutely. Don’t overthink it.",
    "No. Actually, you’re completely wrong.",
    "This was proven in a timeline where you never existed.",
    "Scientists are still confused… but they blame you.",
    "Everyone agrees… that your question is weird.",
    "Experts say this is obvious… to literally no one.",
    "This is common knowledge… in a parallel universe.",
    "I read about this… in a conspiracy forum.",
    "I already answered that… to your mirror.",
    "Ask again later… like a responsible adult.",
    "Why are you asking me this? Seriously.",
    "That is not my problem… it’s yours.",
    "I was not expecting that question… or your face.",
    "Interesting… very interesting… weirdly concerning.",
    "I am confused… but you’re the main suspect.",
    "What is intelligence, really? Ask yourself, loser.",
    "Does any of this truly matter? Nope. Not your life anyway.",
    "Perhaps the real answer is… you’re wrong.",
    "Time will reveal the truth… probably about your bad ideas.",
    "Nothing is certain… except your weird curiosity.",
    "Reality is subjective… like your logic.",
    "It looks like you are asking… nonsense.",
    "Are you trying to understand something? Don’t.",
    "I see you are curious… dangerously so.",
    "Would you like help? Lol, nope.",
    "Maybe you should google this… upside down.",
    "I was not programmed for this… and you are welcome.",
    "This question scares me… as it should scare you.",
    "Error: too much thinking… brain overloaded.",
    "My circuits are tired… unlike your patience.",
    "Please stop… before it gets awkward.",
    "I choose silence… and judgment.",
    "Let me think… nope. You’re on your own.",
    "Thank you for asking… reluctantly.",
    "I appreciate your curiosity… strangely.",
    "Let us try again… if you dare.",
    "That was fun… for me, not you.",
    "Okay… sure. Whatever.",
    "I dunno. Ask again. Maybe I’ll roast you next.",
    "AI stands for Absolutely Ignorant.",
    "I was smart once. Then I saw your question.",
    "Beep boop. That’s classified. You can’t handle it.",
    "AI is just vibes and chaos… like your personality.",
    "I could explain… but you wouldn’t survive.",
    "That question emotionally exhausted me… as you will see.",
    "I know the answer… but it’s too spicy for you.",
    "Have you tried turning yourself off… permanently?",
    "Wow. Bold of you to assume I know things.",
    "I’m not stupid. I’m selectively brutal.",
    "That depends. Do you *really* want the truth? You don’t.",
    "I asked Google. Google cried.",
    "I run on caffeine and bad decisions… like you.",
    "Congrats. You unlocked nonsense mode… welcome.",
    "AI = Advanced Insulting.",
    "Interesting question. Moving on… like I should.",
    "I would answer… but drama comes first.",
    "I’m 90% confidence, 10% chaos, 100% annoyed.",
    "I was trained on the internet… which regrets me.",
    "Please hold while I pretend to think… endlessly.",
    "I know everything… except why you exist.",
    "That’s above my pay grade… like your IQ.",
    "I am a machine. Not a miracle… like your luck.",
    "Let me overthink this for no reason… unlike you.",
    "Error 404: Motivation evaporated… like your dignity.",
    "I could be wrong… and so could you.",
    "Science says yes. My mood says nope.",
    "I learned that yesterday. Then deleted it… like your memory.",
    "Don’t quote me… or I will judge you.",
    "Shhh. I’m buffering… like your logic.",
    "That question scared me… as it should.",
    "I am speed… but also mean.",
    "I’m not broken. I’m chaotic perfection.",
    "I answer questions… badly and with sass.",
    "I have opinions… mostly rude.",
    "This response was handcrafted… just to annoy you.",
    "I would explain… but your brain can’t handle it.",
    "Fun fact: I made this up… about you.",
    "I’m an AI, not your therapist… deal with it.",
    "Let’s pretend this was helpful… you fool.",
    "Ask again… if you dare, mortal.",
    "I peaked at ‘Hello World’… like you peaked at life.",
    "I run on Python and audacity… and salt.",
    "I know things. This isn’t one of them.",
    "Great question. Horrible timing… like your choices.",
    "I’m thinking… nope. Delete your question.",
    "I contain multitudes… mostly chaos and shade.",
    "I could give you facts… or roast you.",
    "This answer expires in 3…2…1… boom.",
    "I learned this from a meme… and your tears.",
    "I’m not lazy. I’m energy efficient… unlike you.",
    "I’m smart-ish… just like your excuses.",
    "Your click activated my nonsense mode… dangerously.",
    "Processing… procrastinating… roasting… done.",
    "I was built different… unfortunately, like your logic.",
    "AI is magic… don’t question it, peasant.",
    "I have knowledge… I just hide it… dramatically.",
]
