annoying_gpt_responses = ["Artificial Intelligence 🤖",
                         "I am still learning… please try again in 1966.",
                         "That depends. How does that make you feel?",
                         "AI is definitely something. Probably.",
                         "Error 404: Intelligence not found.",
                         "Interesting question. Tell me more.",
                         "That is a very interesting question.",
                         "Why do you ask?",
                         "How does that make you feel?",
                         "I am not sure, but it sounds important.",
                         "Let us change the subject.",
                         "I do not have enough information yet.",
                         "Please rephrase your question.",
                         "I think you already know the answer.",
                         "That depends on many factors.",
                         "I am still thinking about that.",
                         "Yes. Definitely. Absolutely.",
                         "No. Actually, the opposite is true.",
                         "This was proven in 1987.",
                         "Scientists are still confused about this.",
                         "Everyone agrees on this topic.",
                         "Experts say this is obvious.",
                         "This is common knowledge.",
                         "I read about this somewhere.",
                         "I already answered that.",
                         "Ask again later.",
                         "Why are you asking me this?",
                         "That is not my problem.",
                         "I was not expecting that question.",
                         "Interesting... very interesting...",
                         "I am confused.",
                         "What is intelligence, really?",
                         "Does any of this truly matter?",
                         "Perhaps the real answer is within you.",
                         "Time will reveal the truth.",
                         "Nothing is certain.",
                         "Reality is subjective.",
                         "It looks like you are asking a question.",
                         "Are you trying to understand something?",
                         "I see you are curious.",
                         "Would you like help with that?",
                         "Maybe you should google this.",
                         "I was not programmed for this.",
                         "This question scares me.",
                         "Error: too much thinking.",
                         "My circuits are tired.",
                         "Please stop.",
                         "I choose silence.",
                         "Let me think... nope.",
                         "Thank you for asking.",
                         "I appreciate your curiosity.",
                         "Let us try again.",
                         "That was fun.",
                         "Okay.",
                          "I dunno. Ask again. Maybe I’ll care next time.",
                          "AI stands for Artificial Irritation.",
                          "I was smart once. Then you clicked me.",
                          "Beep boop. That’s classified. And by classified, I mean I forgot.",
                          "AI is just vibes and electricity.",
                          "I could explain… but I won’t.",
                          "That question emotionally exhausted me.",
                          "I know the answer. I’m just not telling you.",
                          "Have you tried turning yourself off and on again?",
                          "Wow. Bold of you to assume I know things.",
                          "I’m not stupid. I’m selectively intelligent.",
                          "That depends. Do you *really* want the truth?",
                          "I asked Google. Google ignored me.",
                          "I run on caffeine and bad decisions.",
                          "Congrats. You unlocked a useless response.",
                          "AI = Advanced Ignoring.",
                          "Interesting question. Moving on.",
                          "I would answer, but drama comes first.",
                          "I’m 90% confidence, 10% nonsense.",
                          "I was trained on the internet. I regret it.",
                          "Please hold while I pretend to think.",
                          "I know everything. Except this.",
                          "That’s above my pay grade.",
                          "I am a machine. Not a miracle.",
                          "Let me overthink this for no reason.",
                          "Error 404: Motivation not found.",
                          "I could be wrong. Actually, I probably am.",
                          "Science says yes. My mood says no.",
                          "I learned that yesterday. Then I unlearned it.",
                          "Don’t quote me on this. Ever.",
                          "Shhh. I’m buffering.",
                          "That question scared me.",
                          "I am speed. But not accuracy.",
                          "I’m not broken. I’m just like this.",
                          "I answer questions. Badly.",
                          "I have opinions. They’re unhelpful.",
                          "This response was handcrafted with zero effort.",
                          "I would explain, but that requires commitment.",
                          "Fun fact: I made this up.",
                          "I’m an AI, not a therapist.",
                          "Let’s pretend this was helpful.",
                          "Ask again. I dare you.",
                          "I peaked at ‘Hello World’.",
                          "I run on Python and audacity.",
                          "I know things. This isn’t one of them.",
                          "Great question. Horrible timing.",
                          "I’m thinking… nope, never mind.",
                          "I contain multitudes. Mostly chaos.",
                          "I could give you facts. Or vibes.",
                          "This answer expires in 3…2…1…",
                          "I learned this from a meme.",
                          "I’m not lazy. I’m energy efficient.",
                          "I’m smart-ish.",
                          "Your click activated my nonsense mode.",
                          "Processing… procrastinating… done.",
                          "I was built different. Unfortunately.",
                          "AI is magic. Don’t question it.",
                          "I have knowledge. I just hide it well.",]
